MetronicApp.controller('department', ['$rootScope', '$scope', '$state', '$stateParams', '$http', function ($rootScope, $scope, $state, $stateParams, $http) {
    // $('#scroll-to-top').click();


    //$scope.departmentId = $stateParams.departmentId;
    $http.get(domain + '?action=getStatisticsByUnit&unit=department&id=' + $stateParams.departmentId)
    .success(function (data) {
        if (data.status == 'ok') {
            $scope.statistics = data.data;

            $scope.courses = data.data.statisticsByCourse;
            for (i = 0; i < $scope.courses.length; i++) {
                $scope.courses[i].completedPercent = $scope.courses[i].employees * $scope.courses[i].ended / 100;
            }
            console.log($scope.statistics)
        }
    })
    .error(function (data) {
        console.log(data);
    })

    $scope.getEmployeesByCourse = function (courseId) {
        $http.get(domain + '?action=getStatisticsByUnit&unit=employeesStatus&departmentId=' + $stateParams.departmentId + '&courseId=' + courseId)
    .success(function (data) {
        console.log(data)
        if (data.status == 'ok') {
            $scope.courseDetails = data.data.general;
            $scope.employees = data.data.employees;

            console.log($scope.employees);
            initTable1();
        }
    })
    .error(function (data) {
        console.log(data);
    })
    }

    var initTable1 = function () {
        $('#employeesTable').DataTable({
            dom: 'T<"clear">lfrtip',
            tableTools: {
                "sSwfPath": "../../../assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf"
            }
        });
    }

    //var initTable1 = function () {


    //    var table = $('#employeesTable');

    //    /* Table tools samples: https://www.datatables.net/release-datatables/extras/TableTools/ */

    //    /* Set tabletools buttons and button container */

    //    $.extend(true, $.fn.DataTable.TableTools.classes, {
    //        "container": "btn-group tabletools-dropdown-on-portlet",
    //        "buttons": {
    //            "normal": "btn btn-sm default",
    //            "disabled": "btn btn-sm default disabled"
    //        },
    //        "collection": {
    //            "container": "DTTT_dropdown dropdown-menu tabletools-dropdown-menu"
    //        }
    //    });

    //    var oTable = table.dataTable({

    //        // Internationalisation. For more info refer to http://datatables.net/manual/i18n
    //        "language": {
    //            "aria": {
    //                "sortAscending": ": activate to sort column ascending",
    //                "sortDescending": ": activate to sort column descending"
    //            },
    //            "emptyTable": "No data available in table",
    //            "info": "Showing _START_ to _END_ of _TOTAL_ entries",
    //            "infoEmpty": "No entries found",
    //            "infoFiltered": "(filtered1 from _MAX_ total entries)",
    //            "lengthMenu": "Show _MENU_ entries",
    //            "search": "Search:",
    //            "zeroRecords": "No matching records found"
    //        },

    //        "order": [
    //            [0, 'asc']
    //        ],
    //        
    //        "lengthMenu": [
    //            [5, 15, 20, -1],
    //            [5, 15, 20, "All"] // change per page values here
    //        ],
    //        // set the initial value
    //        "pageLength": 10,

    //        "dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r><'table-scrollable't><'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>", // horizobtal scrollable datatable

    //        // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
    //        // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js). 
    //        // So when dropdowns used the scrollable div should be removed. 
    //        //"dom": "<'row' <'col-md-12'T>><'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

    //        "tableTools": {
    //            "sSwfPath": "../../../assets/global/plugins/datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",
    //            "aButtons": [{
    //                "sExtends": "pdf",
    //                "sButtonText": "PDF"
    //            }, {
    //                "sExtends": "csv",
    //                "sButtonText": "CSV"
    //            }, {
    //                "sExtends": "xls",
    //                "sButtonText": "Excel"
    //            }, {
    //                "sExtends": "print",
    //                "sButtonText": "Print",
    //                "sInfo": 'Please press "CTR+P" to print or "ESC" to quit',
    //                "sMessage": "Generated by DataTables"
    //            }]
    //        }
    //    });

    //    var tableWrapper = $('#employeesTable_wrapper'); // datatable creates the table wrapper by adding with id {your_table_jd}_wrapper

    //          tableWrapper.find('.dataTables_length select'); // initialize select2 dropdown
    //}

    //initTable1();


} ])